import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
import './rankd-button-fixes.css'
import './mobile-header-consistency.css'
import './rankd-social-share.css'
import './activity-share-buttons.css'
import './rankd-guest-share-vote.css'
import './public-shared-content.css'
import './show-data-refresh-button.css'
import './remove-show-data-refresh-button.css'
import './dashboard-premiering-soon.css'
import './dashboard-loading-screen.css'
import './firefox-mobile-nav-fix.css'
import './notification-alerts.css'
import './public-show-watch-providers.css'
import './creator-profile-chats.css'
import './creator-list-comments.css'
import './following-list-card-consistency.css'
import './rankd-scroll-fix.js'
import './rankd-social-share.js'
import './dashboard-airing-link-fix.js'
import './activity-share-buttons.js'
import './rankd-guest-share-vote.js'
import './rankd-shared-stats-fix.js'
import './public-shared-content.js'
import './show-data-refresh-button.js'
import './dashboard-premiering-soon.js'
import './dashboard-loading-screen.js'
import './notification-nav-badge.js'
import './notification-deep-links.js'
import './notification-copy-cleanup.js'
import './public-show-watch-providers.js'
import './creator-profile-chats.js'
import './creator-list-comments.js'
import './following-list-card-consistency.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
